server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5678/commercehub_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:V29ya2luZ0hhcmRPbkNvbW1lcmNlSHViUHJvamVjdDIwMjZTZWN1cmVLZXlWMzg5NDU=}
  expiration: 86400000 # Thời gian sống của Access Token 1 ngày = 86400000 ms
  refreshExpiration: 604800000 # Thời gian sống của Refresh Token7 ngày = 604800000 ms